### ISSUE TITLE
UDP Communication not working under linux dockers

### ISSUE THREAD

**Issue by arthurcbsouza** [DarkRiftNetworking/DarkRift#117] opened 2021-05-21 08:15 UTC
### Quick Description
When connect only one player the packet arrive on server but with more than one is connected, not a single package arrives on the server

### Explanation
I'm trying to put my server game to run under linux, to doign this i tested many LINUX version ( Ubuntu, Mono, CentOS, Alpine, Debian )
To run into native .Net i tried MONO, and the result is when one single playr is connected the packages arrive, but in case of i tried to put 2 players the packages isn't arrived.
I wondering if the reason was the native .Net isn't working under linux, so i migrated everthing to .Net Core and generated a docker, but unfortunelly i had the exaclty same result no matter if i try to run into a .Net Core or MONO library in any LINUX distribution.

#### For Issues
Is easy to reproduce, just create a game server and put into a docker and try to send and receive UDP packages using Unreliable mode, as easy as it is.

**Comment by JamJar00** [comment] 2021-06-12 16:35
Hey!

A user on the Discord (I think it was you, OnlineObject) posted this that I think is related:
> @Jamster  Hi dude.. after search a lot i found a document regard to .Net Core that mention a possible bug into, the exactly same issue that i have been challenging, but unsolved, nonetheless with on important tip about socket configuration... So i started to investigate and ended up into realizing that the socket on server side need to be configured with "SO_REUSEADDR"  and "SO_REUSEPORT".. To be short, is i put noDelay = false, and server start to accept more than one UDP connection, with this value equals true the problem brings back....
>
> My research is based on this post, which make-me check "SocketOptionName" which have a value "noDelay", which make-me try to disable to check... I really  can't understand, because ( as far as i analyzed the code ) .. noDelay should affect only TCP connection ( not UDP ) .. Anyway seems working, and i'm going to make more tests to evaluate results
>
> https://github.com/dotnet/runtime/issues/30782

Looks like the fix should be fairly simple. Were you able to test this configuration out?

I've not been able to reproduce with the steps you provided example, but I haven't played around with the socket setting you mentioned or the NoDelay option yet.

**Comment by arthurcbsouza** [comment] 2021-06-12 16:58
Hi dude.. 
    Yeah.. OnlineOnbject it's me :D
    What I did was basically create a Linux Docker and run my game into it.. I have already tested into Mono and .Net Core, and always with the same results...
    Right now I give up running Linux under Playefab due to a lot of instabilities, but when I run into a local Docker ( without PlayFab ) it's running pretty well... I"m using .Net Core and it's quite complicated because you need to prepare his environment and projects to deploy into a docker.. 
    I'm trying to found a time to create a guideline and share a template project with anyone who tries to have DR under Linux Dockers.
    But if you really want to test it just create a docker and execute.

# DockerFile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

# To run with MONO
FROM mono:latest

EXPOSE 4296/udp
EXPOSE 4296/tcp

# assuming that you have dockerFile into a you game build ( into the rot )
COPY . ./

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 
CMD ["mono", "./YourServer.exe"]

# How to execute you game
# docker build -t game_server .
# docker run -it -p 4296:4296/udp -p 4296:4296/tcp --name mygame game_server

Reagrds
Arthur

**Comment by JamJar00** [comment] 2021-06-13 12:22
It sounds like this isn't a DarkRift issue but actually an issue with Playfab/deployment on Playfab, given that running it locally in Docker is working fine, so I'm going to close this issue. If you disagree we can always open it again.

In testing out this issue I [added support for running the DarkRift CLI in Docker](https://github.com/DarkRiftNetworking/darkrift-cli#docker) so (while I don't think that will sort the Playfab issue out) it might help you out a bit!

**Closed by JamJar00** 2021-06-13 12:22 UTC
Labels: Bug, Question, Server
